spring:
  application:
    name: Platica
  datasource:
    url: jdbc:postgresql://localhost:54321/postgres?currentSchema=platica
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
    clean-disabled: true
    clean-on-validation-error: true
  jackson:
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/gubrit
          jwk-set-uri: http://localhost:8081/auth/realms/gubrit/protocol/openid-connect/certs
